apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: frontend-app
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/kuflink/frontend-app:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev_frontend
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/kuflink/frontend-app:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: frontend-app
        chartPath: charts/frontend-app
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/kuflink/frontend-app'
          image.tag: '{{.DIGEST_HEX}}'
